version: '3.8'
services: 
  mongodb:
    image: mongo:5.0.2
    ports:
      - 27017:27017
    container_name: mongo-db

  backend:
    depends_on:
      - mongodb
    build:
      context: ./url-shortener-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: api
    environment:
      - MONGO_URL=mongodb://db:27017/url-shortener
  
  frontend:
    build:
      context: ./url-shortener-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: ui
    environment:  
      - BACKEND_URL=http://localhost:3000/urls
volumes:
  db: